###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.3.101
#      host: 127.0.0.1
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
#        id必须配置，且不能以数字开头，类似变量一样
        instance-id: ${spring.application.name}
#        以ip方式注册，不能以主机名字，因为consul在另一台主机，不能解析服务所在的主机名（真nmb坑）
        prefer-ip-address: true
#        heartbeat:
#          enabled: true
