server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.101:1111 #nginx 负载均衡
management:
  endpoints:
    web:
      exposure:
        include: '*'
