server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.101:2222
management:
  endpoints:
    web:
      exposure:
        include: '*'
