server:
  port: 9527
spring:
  application:
   name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启从注册中心动态路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
#            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2021-05-07T15:28:56.876+08:00[Asia/Shanghai]
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
#            - Cookie=username,lyc
#            - Header=X-Request-Id,\d+
#            - Host=**.lyc.com
            - Method=GET
#            - Query=red
#            - RemoteAddr=192.168.3.1/24   #规定允许访问的ip段  (用虚拟机访问  CIDR表示法见笔记)
#            - Weight=group1,2


        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由


eureka:
  instance:
#    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service
    prefer-ip-address: true
  client:
    service-url:
      register-with-ereka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

